version: '3'

networks:
  default:
    driver: bridge

services:

  geotiff:
    container_name: geotiff
    image: geotiff:latest
    build:
      context: ./
    ports:
      - "8080:8080"
    volumes:
      - "./data:/data"
    # environment:
    #   - LOG_REQUEST=true
    #   - MAX_PARALLEL_REQUESTS=10
