FROM osgeo/gdal:ubuntu-small-latest
#https://github.com/OSGeo/gdal/blob/master/docker/alpine-small/Dockerfile

RUN curl -sL https://deb.nodesource.com/setup_18.x | bash -
RUN apt-get update -y && apt-get install -y \
	build-essential \
	libgdal-dev \
	nodejs \
	&& rm -rf /var/lib/apt/lists/*

WORKDIR /home

COPY ./ ./

RUN npm install
RUN cd server && npm install
RUN rm -fr node_modules/gdal-next/src

CMD ["node", "server/server.js"]
