/*
 * GeoPicker-cli
 * Copyright Stefano Cudini stefano.cudini@gmail.com
 * https://opengeo.tech
 */

const path = require('path')
    , { program } = require('commander');

function loadAndValidateConfig(file) {
  const parserConfig = require('../server/parserConfig')
      , configPath = file || path.join(__dirname, '../server/config.yml')
      , basepath = path.dirname(configPath)
      , configfile = path.basename(configPath);

  const config = parserConfig.load({basepath, configfile});
  parserConfig.validateConfig(config, './schemas/config');

  return {config, configPath};
}

module.exports = process => {

  const { Console } = require('console')
      , console = new Console(process.stderr);

  program
    .command('config-validate [file]')
    .description('validate a config.yml file against the GeoPicker config schema')
    .action(file => {
      try {
        const {configPath} = loadAndValidateConfig(file);
        console.log(`${configPath} valido`);
      } catch (e) {
        console.error(e.message);
        process.exit(1);
      }
    });

  program
    .command('config-show [file]')
    .description('print the parsed config.yml object as JSON')
    .action(file => {
      try {
        const {config} = loadAndValidateConfig(file);
        console.log(JSON.stringify(config, null, 2));
      } catch (e) {
        console.error(e.message);
        process.exit(1);
      }
    });

  program
    .command('server-start')
    .description('start the GeoPicker HTTP server')
    .action(() => {
      require('../server/server.js');
    });

  program
    .command('server-status')
    .description('show the status JSON of the running GeoPicker HTTP server (same as the /status endpoint)')
    .action(() => {
      const {config} = loadAndValidateConfig()
          , {port, host, prefix} = config
          , hostname = host === '0.0.0.0' ? '127.0.0.1' : host
          , url = `http://${hostname}:${port}${prefix.endsWith('/') ? prefix : prefix + '/'}status`;

      require('http').get(url, res => {
        let body = '';
        res.on('data', chunk => { body += chunk });
        res.on('end', () => process.stdout.write(body + '\n'));
      }).on('error', e => {
        console.error(`server not reachable at ${url}: ${e.message}`);
        process.exit(1);
      });
    });

  program
    .command('completion')
    .description('generate a bash completion script for the geopicker command')
    .action(() => {
      const cmds = program.commands.map(c => c.name())
          , opts = program.options.flatMap(o => [o.short, o.long]).filter(Boolean)
          , words = cmds.concat(opts).join(' ');

      process.stdout.write(`# bash completion for geopicker, generated by "geopicker completion"
_geopicker_completions() {
  local cur prev
  cur="\${COMP_WORDS[COMP_CWORD]}"
  prev="\${COMP_WORDS[COMP_CWORD-1]}"
  case "$prev" in
    -d|--dataset|-i|--input-file)
      COMPREPLY=( $(compgen -f -- "$cur") )
      return 0
      ;;
  esac
  if [[ $COMP_CWORD -eq 1 ]]; then
    COMPREPLY=( $(compgen -W "${words}" -- "$cur") )
  else
    COMPREPLY=( $(compgen -f -- "$cur") )
  fi
}
complete -F _geopicker_completions geopicker
`);
    });

  program
    .option('-g, --get <lon,lat>', `pick only values from dataset by longitude and latitude param`)
    .option('-s, --set', 'set properties in the input geojson picking values from dataset')
    .option('-d, --dataset <file>', 'input dataset file like a raster .tif')
    .option('-i, --input-file <file>', 'input geojson file')
    .option('-t, --timing', 'print processing time', false)
    .option('-v, --verbose', 'print verbose output', false)
    .action(opts => {
      if (!opts.dataset) {
        program.error("error: required option '-d, --dataset <file>' not specified");
      }

      const fs = require('fs')
          , geopicker = require('../lib/geopicker')
          , { setValue, getValue, utils: { parseLocations } } = geopicker;

      const {dataset, inputFile, timing, get, set, verbose} = opts;

      if(timing)  {
        console.time('Processing');
      }

      const inputGeojson = inputFile ? JSON.parse(fs.readFileSync(inputFile,'utf-8')) : null;

      if(verbose) {
        process.stdout.write(('Input:\n'+ JSON.stringify(inputGeojson, null, 4))+'\n');
        process.stdout.write('Output:\n');
      }

      if(set && inputGeojson) {
        setValue(inputGeojson, dataset);
        process.stdout.write(JSON.stringify(inputGeojson,null,4));
      }
      else if(get) {
        const locs = parseLocations(get,'_');
        const values = getValue(locs, dataset);
        process.stdout.write(JSON.stringify(values,null,4)+'\n');
      }

      if(timing)  {
        console.timeEnd('Processing');
      }
    });

  if (process.argv.length <= 2) {
    program.help();
  }

  program.parse(process.argv);
}
