environments:
  default: prod
#   #default environment if NODE_ENV is not defined

prod:
  port: 8080
dev:
  port: 9090
  datapath: 'tests/data/'

cors:
  origin: '*'
  optionsSuccessStatus: 200
  #some legacy browsers (IE11, various SmartTVs) choke on 2

logger:
  transport:
    target: 'pino-pretty'

datapath: '/data/'
rasters:
  default:
    path: trentino-altoadige_dem_90m.tif
    #epsg: 4326
    #band: 1
  elevation:
    path: trentino-altoadige_dem_90m.tif
  dem:
    path: trentino-altoadige_dem_90m.tif
  # aspect:
  #   path: trentino-altoadige_aspect_90m.tif
  # slope:
  #   path: trentino-altoadige_slope_90m.tif

pixel:
  max_locations: 10000
  #maximum number of locations picked in a single request
  prec_digits: 5
  #number of digits precision returned in geojson coordinates

linestring:
  max_locations: 10000
  prec_digits: 5
  #number of digits precision returned in geojson coordinates

densify:
  length: 90
  units: 'meters'

errors:
  nodatadir: "data directory not exists"
  densify_nobody: "send a post with geojson in body"