environments:
  default: prod
#   #default environment if NODE_ENV is not defined

prod:
  port: 8080
  host: 0.0.0.0
  datapath: '/data'
  # to test prod end utside docker datapath: ./tests/data
dev:
  port: 9090
  host: 127.0.0.1
  datapath: ./tests/data
  fastifyConf:
    logger:
      level: 'debug'
      transport:
        target: 'pino-pretty'

cors:
  origin: '*'
  optionsSuccessStatus: 200
  #some legacy browsers (IE11, various SmartTVs) choke on 2

fastifyConf:
  maxParamLength: 1024
  logger:
    level: 'info'
    transport:
      target: 'pino-pretty'

demopage: ${DEMO_PAGE}
demopath: '/map'

# TODO group in limits section
max_locations: 10000
#maximum number of locations picked in a single request
prec_digits: 5
#number of digits precision returned in geojson coordinates

#default densify options
densify:
  length: 90
  units: 'meters'

errors:
  nodatadir: "Data directory not exists"
  nodefaultdataset: "Default dataset file not exists"
  nodataset: "Dataset name not exists"
  densify_nobody: "Require a geojson in body"
  nolocations: "Require array of locations"

datasets:
  default: elevation
  #aliases of same dataset
  altitude: elevation
  elevation:
    path: trentino-altoadige_dem_90m.tif
    band: 1
    epsg: 4326
  aspect:
    path: italia_aspect_30m.tif
    band: 2
    epsg: 4326
  elevation_veneto:
    path: veneto_30m.tif
    #band: * #TODO espose all bands if value is *
  #TODO manage shape
  #  admins:
  #   path: a-shape-file.shp
