version: '3'

networks:
  default:
    driver: bridge

services:

  geopicker:
    container_name: geopicker
    image: geopicker:latest
    build:
      context: ../
      dockerfile: ./server/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - "../tests/data:/data"
    environment:
      - PREFIX=/geopicker
      - DEMO_PAGE=true
      #TODO- SWAGGER_PAGE=true
    restart: always

  # test:
  #   container_name: geopicker-test
  #   image: geopicker-test:latest
  #   build:
  #     context: ../
  #     dockerfile: ./tests/Dockerfile.alpine
  #     #dockerfile: ./tests/Dockerfile.osgeo
  #   ports:
  #     - "8081:8080"
  #   volumes:
  #     - "../tests/data:/data"
  #   environment:
  #     - DEMO_PAGE=true
