version: '3'

networks:
  default:
    driver: bridge

services:

  geotiff:
    container_name: geotiff-picker
    image: geotiff-picker:latest
    build:
      context: ../
      dockerfile: ./server/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - "../index.html:/server/index.html"
      - "../tests/data:/data"
    environment:
      - DEMO_PAGE=true

  # test:
  #   container_name: geotiff-picker-test
  #   image: geotiff-picker-test:latest
  #   build:
  #     context: ../
  #     dockerfile: ./server/Dockerfile.alpine
  #     #dockerfile: ./server/Dockerfile.osgeo
  #   ports:
  #     - "8081:8080"
  #   volumes:
  #     - "../tests/data:/data"
