version: '3'

networks:
  default:
    driver: bridge

services:

  geotiff:
    container_name: geotiff
    image: geotiff:latest
    build:
      context: ../
      dockerfile: ./server/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - "./tests/data:/data"

  buster:
    container_name: geotiff-buster
    image: geotiff-buster-slim:latest
    build:
      context: ../
      dockerfile: ./server/Dockerfile.buster-slim
    ports:
      - "8080:8080"
    volumes:
      - "./tests/data:/data"
