version: '3'

networks:
  default:
    driver: bridge

services:

  # geopicker-official:
  #   container_name: geopicker
  #   image: stefcud/geopicker:1.2.5
  #   ports:
  #     - "127.0.0.1:8080:8080"
  #   volumes:
  #     - "../tests/data:/data"
  #   environment:
  #     - PREFIX=$PREFIX
  #     - DEMO_PAGE=true
  #     - DATASET_DEFAULT=$DATASET_DEFAULT
  #     #TODO- SWAGGER_PAGE=true
  #   restart: always

  geopicker:
    container_name: geopicker
    image: stefcud/geopicker:latest
    build:
      context: ../
      dockerfile: ./server/Dockerfile
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - "../tests/data:/data"
      #- "./custom.config.yml:/home/server/config.yml"
      #- "../index.html:/home/index.html"
    environment:
      - PREFIX=$PREFIX
      - DEMO_PAGE=true
      - DATASET_DEFAULT=$DATASET_DEFAULT
      #TODO- SWAGGER_PAGE=true
    restart: always

  # test:
  #   container_name: geopicker-test
  #   image: geopicker-test:latest
  #   build:
  #     context: ../
  #     dockerfile: ./tests/Dockerfile.alpine
  #     #dockerfile: ./tests/Dockerfile.osgeo
  #   ports:
  #     - "8081:8080"
  #   volumes:
  #     - "../tests/data:/data"
  #   environment:
  #     - DEMO_PAGE=true
